version: '3.4'

services:
  
  mock-service:
    image: mockservice
    build:
      context: .
      dockerfile: MockService/Dockerfile

  another-mock-service:
    image: anothermockservice
    build:
      context: .
      dockerfile: AnotherMockService/Dockerfile
  
  heartbeat-ekg:
    image: heartbeatekg
    build:
      context: .
      dockerfile: Heartbeat.EKG/Dockerfile

#networks:
#  default:
#    external:
#      name: imperium